model_params:
  name: 'VanillaVAE' # VAE 模型的名字
  in_channels: 3
  latent_dim: 128

exp_params:
  dataset: celeba
  data_path: "data/celebA/" # 数据集的路径
  img_size: 64 # 模型准备在这个 Size 下工作
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 50
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE" # 实验名称
  manual_seed: 1265
